# Generated by Django 5.0.4 on 2024-04-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="answer",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="question",
            field=models.CharField(default="1", max_length=255),
            preserve_default=False,
        ),
    ]
